name: poisson_warp
description: a high‑precision gravitational‑physics and time‑deformation engine developed in Puerto Rico. Built on a foundation of arbitrary‑precision mathematics using the big_dec library, it models how mass, geometry, and orbital motion shape the flow of time and the evolution of celestial bodies. The engine specializes in N-body simulations, relativistic time-dilation calculations, and frame transformations to align simulated data with high-fidelity observational sources like NASA JPL Horizons.
version: 0.0.4+4
repository: https://github.com/LiveUser/poisson_warp

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  big_dec: ^0.1.8+18
  power_plant: ^1.0.2+3
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  http: ^1.6.0
