name: poisson_warp
description: A library inspired by poisson's ratio to calculate the relative factor at which time ticks in different bodies in the cosmos.
version: 0.0.2+2
repository: https://github.com/LiveUser/poisson_warp

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  big_dec: ^0.0.9+9
  power_plant: ^1.0.2+3
  
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
